### ISSUE TITLE
Renfe Data

### ISSUE THREAD

**Issue by gtrabanco** [gerardcl/renfe-cli#194]
**Describe the solution you'd like**
Maybe you know it and you have choosen to scrape renfe site instead but there is a open json data of Renfe Schedules and stations in this link:
- https://data.renfe.com/dataset?tags=horarios

**Describe alternatives you've considered**
I have considered use it but due I am living in North and Feve does not respect schedules at all it is not an option for me. But, there is a platform called "Elcano" which can provide realtime data of the trains.

- https://www.adif.es/w/elcano

I have been sniffing traffic because there is no info to use it by public people but you can scrape adif, it provides realtime just for current train which makes sense but if the train is stopped at any station waiting for other (because there is only one rail) it doesn't provide that info just update the train arriving time after some time.

The api in phones use firebase to register an id for the user (I think based on installation id) and later you can access elcano api but I am not really sure about all this process because I haven't tested yet. The difference is that in phone you can view almost real position of the train and not only the time to arrive in the station.

**Additional context**

Hope this info is helpful.

**Comment by gerardcl** [comment]
Hi @gtrabanco!

Thanks for the infos!

I did not know about the adif API, looks really interesting, but I understand it is about status but not schedules.

Regarding the renfe data, in the past a colleague informed me about that too, I looked into it by then (and I also did review it now again) and I decided to keep on real-time scraping the site since I found out it has more accurate/up-to-date schedules.

I would love renfe site to be a modern site and avoid to launch a headless browser to scrape it, but the more this site evolves the more complex it is getting (I do not want to imagine the guys that jump time to time to maintain or add new features). They look like only applying patches instead of remaking it in a proper, reliable and secure way.

Thanks again and happy to get contributions any time! :+1: 

Best regards,

**Comment by gerardcl** [comment]
FYI @gtrabanco --> https://github.com/gerardcl/renfe-cli/actions/runs/8774260521/job/24587873455
It looks like randomly now the page used for `renfe-cli` to scrape the timetables is now constantly under maintenance (since weeks now...).

I guess, if we want to keep this CLI alive we might need to finally shift to one of the two proposals you made (since I don't want to parse this crap site anymore).

Do you know if the https://ssl.renfe.com/gtransit/Fichero_AV_LD/google_transit.zip file is really accurate and trustworthy?
